# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(default='0000000000', max_length=12)),
                ('room_no', models.CharField(max_length=10)),
                ('queue_rear_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reception',
            name='mobile_no',
            field=models.CharField(default='0000000000', max_length=12),
        ),
    ]
