# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20180307_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='room_no',
            field=models.CharField(max_length=100),
        ),
    ]
