# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_auto_20180307_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reception',
            new_name='user_details',
        ),
    ]
