# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_auto_20180307_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='queue_rear_no',
            new_name='queue_no',
        ),
        migrations.AddField(
            model_name='user_details',
            name='appointment_num',
            field=models.CharField(default='Not yet appointed', max_length=50),
        ),
        migrations.AddField(
            model_name='user_details',
            name='disease',
            field=models.CharField(default='Healthy', max_length=100),
        ),
        migrations.AddField(
            model_name='user_details',
            name='prescription',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
