# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_user_details_doctor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='appointment_num',
            new_name='appointment_no',
        ),
    ]
