# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_auto_20180308_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_no', models.CharField(max_length=50)),
                ('doctor_associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.doctor')),
            ],
        ),
    ]
