# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_queue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='queue_no',
            new_name='max_queue_no',
        ),
    ]
