# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_auto_20180308_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cur_queue_no',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
