# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0011_queue_user_associated'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=50)),
                ('pres', models.CharField(default='Not yet prescribed', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='prescription',
        ),
        migrations.AddField(
            model_name='prescription',
            name='user_associated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.user_details'),
        ),
    ]
