# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0012_auto_20180309_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='disease',
        ),
        migrations.AddField(
            model_name='prescription',
            name='disease',
            field=models.CharField(default='Not yet identified', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='symptoms',
            field=models.CharField(default="Don't know", max_length=100),
        ),
    ]
